/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EscribirRouteImport } from './routes/escribir'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartasIndexRouteImport } from './routes/cartas.index'
import { Route as CartasIdRouteImport } from './routes/cartas.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EscribirRoute = EscribirRouteImport.update({
  id: '/escribir',
  path: '/escribir',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartasIndexRoute = CartasIndexRouteImport.update({
  id: '/cartas/',
  path: '/cartas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartasIdRoute = CartasIdRouteImport.update({
  id: '/cartas/$id',
  path: '/cartas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/escribir': typeof EscribirRoute
  '/sobre': typeof SobreRoute
  '/cartas/$id': typeof CartasIdRoute
  '/cartas/': typeof CartasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/escribir': typeof EscribirRoute
  '/sobre': typeof SobreRoute
  '/cartas/$id': typeof CartasIdRoute
  '/cartas': typeof CartasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/escribir': typeof EscribirRoute
  '/sobre': typeof SobreRoute
  '/cartas/$id': typeof CartasIdRoute
  '/cartas/': typeof CartasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/escribir' | '/sobre' | '/cartas/$id' | '/cartas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/escribir' | '/sobre' | '/cartas/$id' | '/cartas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/escribir'
    | '/sobre'
    | '/cartas/$id'
    | '/cartas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EscribirRoute: typeof EscribirRoute
  SobreRoute: typeof SobreRoute
  CartasIdRoute: typeof CartasIdRoute
  CartasIndexRoute: typeof CartasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escribir': {
      id: '/escribir'
      path: '/escribir'
      fullPath: '/escribir'
      preLoaderRoute: typeof EscribirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartas/': {
      id: '/cartas/'
      path: '/cartas'
      fullPath: '/cartas/'
      preLoaderRoute: typeof CartasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartas/$id': {
      id: '/cartas/$id'
      path: '/cartas/$id'
      fullPath: '/cartas/$id'
      preLoaderRoute: typeof CartasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EscribirRoute: EscribirRoute,
  SobreRoute: SobreRoute,
  CartasIdRoute: CartasIdRoute,
  CartasIndexRoute: CartasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
